{
 "title": "SolarThing Dashboard",
 "description": "The SolarThing dashboard that shows the status of the solar panels and batteries.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Battery Voltages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "aliasBy": "$field_packet.identityInfo.displayName",
     "constant": 6.5,
     "dataPath": "data.batteryVoltage",
     "groupBy": "packet.identifier.representation",
     "queryText": "{\n        data:queryStatus(from:\"$timeFrom\", to:\"$timeTo\", sourceId:\"default\") {\n            batteryVoltage {\n                Time:dateMillis\n                packet {\n                    batteryVoltage\n                    identifier { representation }\n                    identityInfo { displayName }\n                }\n            }\n        }\n    }"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data.batteryVoltage",
     "measurement": "solarthing",
     "queryText": "{\n  data:queryStatusLast(to:\"$timeTo\", sourceId:\"default\") {\n    batteryVoltage {\n      Time:dateMillis\n      packet {\n        batteryVoltage\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "batteryVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Device Mode",
   "type": "table",
   "description": "The mode that each device is in",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "alias": "[[tag_identifier]]",
     "constant": 6.5,
     "dataPath": "data.fxStatus, data.mxStatus, data.roverStatus",
     "groupBy": "packet.identifier.representation",
     "measurement": "solarthing",
     "query": "SELECT \"operatingModeName\" FROM \"normal_short_retention\".\"solarthing\" WHERE (\"packetType\" = 'FX_STATUS') AND $timeFilter GROUP BY \"identifier\" ORDER BY DESC LIMIT 1",
     "queryText": "{\n  data:queryStatusLast(to:\"$timeTo\", sourceId:\"default\", reversed: true) {\n    fxStatus {\n      packet {\n        identityInfo { displayName }\n        modeName:operatingModeName\n        identifier { representation }\n      }\n    }\n    mxStatus {\n      packet {\n        identityInfo { displayName }\n        modeName:chargerModeName\n        identifier { representation }\n      }\n    }\n\n    roverStatus {\n      packet {\n        identityInfo { displayName }\n        modeName:chargingStateName\n        identifier { representation }\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "operatingModeName" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "FX_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "PV Wattage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "[[tag_identifier]]",
     "aliasBy": "$field_packet.identityInfo.displayName",
     "constant": 6.5,
     "dataPath": "data.mxStatus",
     "groupBy": "packet.identifier.representation",
     "measurement": "solarthing",
     "query": "SELECT \"pvCurrent\" * \"inputVoltage\" FROM \"solarthing\" WHERE (\"packetType\" = 'MXFM_STATUS') AND $timeFilter GROUP BY \"identifier\"",
     "queryText": "{\n  data:queryStatus(from:\"$timeFrom\", to:\"$timeTo\", sourceId:\"default\") {\n    mxStatus {\n      Time:dateMillis\n      packet {\n        pvWattage  # TODO change\n        identifier {representation}\n        identityInfo { displayName }\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "pvCurrent" ], "type": "field" }
      ],
      [
       { "params": [ "inputVoltage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "MXFM_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Daily kWH",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "MX: [[tag_identifier]]",
     "aliasBy": "$field_packet.identityInfo.displayName",
     "constant": 6.5,
     "dataPath": "data.mxStatus",
     "groupBy": "packet.identifier.representation",
     "measurement": "solarthing",
     "query": "SELECT \"dailyKWH\" FROM \"solarthing\" WHERE (\"packetType\" = 'MXFM_DAILY') AND $timeFilter GROUP BY \"identifier\"",
     "queryText": "{\n  data:queryStatus(from:\"$timeFrom\", to:\"$timeTo\", sourceId:\"default\") {\n    mxStatus {\n      Time:dateMillis\n      packet {\n        dailyKWH\n        identifier {representation}\n        identityInfo { displayName }\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "dailyKWH" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "MXFM_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "[[tag_identifier]]",
     "aliasBy": "$field_packet.identityInfo.displayName",
     "constant": 6.5,
     "dataPath": "data.fxStatus",
     "groupBy": "packet.identifier.representation",
     "measurement": "solarthing",
     "query": "SELECT (\"inverterCurrent\" * \"outputVoltage\") + (\"buyCurrent\" - \"chargerCurrent\") * \"inputVoltage\" FROM \"solarthing\" WHERE (\"packetType\" = 'FX_STATUS') AND $timeFilter GROUP BY \"identifier\"",
     "queryText": "{\n  data:queryStatus(from:\"$timeFrom\", to:\"$timeTo\", sourceId:\"default\") {\n    fxStatus {\n      Time:dateMillis\n      packet {\n        powerUsageWattage\n        identifier {representation}\n        identityInfo { displayName }\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "inverterCurrent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "FX_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Generator Charging",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "[[tag_identifier]]",
     "aliasBy": "$field_packet.identityInfo.displayName",
     "constant": 6.5,
     "dataPath": "data.fxStatus",
     "groupBy": "packet.identifier.representation",
     "measurement": "solarthing",
     "query": "SELECT \"chargerCurrent\" * \"inputVoltage\" FROM \"solarthing\" WHERE (\"packetType\" = 'FX_STATUS') AND $timeFilter GROUP BY \"identifier\"",
     "queryText": "{\n  data:queryStatus(from:\"$timeFrom\", to:\"$timeTo\", sourceId:\"default\") {\n    fxStatus {\n      Time:dateMillis\n      packet {\n        chargerWattage\n        identifier {representation}\n        identityInfo { displayName }\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "chargerCurrent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "FX_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Load on Battery",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "[[tag_identifier]]",
     "aliasBy": "$field_packet.identityInfo.displayName",
     "constant": 6.5,
     "dataPath": "data.fxStatus",
     "groupBy": "packet.identifier.representation",
     "measurement": "solarthing",
     "query": "SELECT \"inverterCurrent\" * \"outputVoltage\" FROM \"solarthing\" WHERE (\"packetType\" = 'FX_STATUS') AND $timeFilter GROUP BY \"identifier\"",
     "queryText": "{\n  data:queryStatus(from:\"$timeFrom\", to:\"$timeTo\", sourceId:\"default\") {\n    fxStatus {\n      Time:dateMillis\n      packet {\n        inverterWattage\n        identifier {representation}\n        identityInfo { displayName }\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "inverterCurrent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "FX_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Generator Buying",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "[[tag_identifier]]",
     "aliasBy": "$field_packet.identityInfo.displayName",
     "constant": 6.5,
     "dataPath": "data.fxStatus",
     "groupBy": "packet.identifier.representation",
     "measurement": "solarthing",
     "query": "SELECT \"buyCurrent\" * \"inputVoltage\" FROM \"solarthing\" WHERE (\"packetType\" = 'FX_STATUS') AND $timeFilter GROUP BY \"identifier\"",
     "queryText": "{\n  data:queryStatus(from:\"$timeFrom\", to:\"$timeTo\", sourceId:\"default\") {\n    fxStatus {\n      Time:dateMillis\n      packet {\n        buyWattage\n        identifier {representation}\n        identityInfo { displayName }\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "chargerCurrent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "FX_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Charger Wattage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "aliasBy": "$field_packet.identityInfo.displayName",
     "constant": 6.5,
     "dataPath": "data.mxStatus",
     "groupBy": "packet.identifier.representation",
     "measurement": "solarthing",
     "query": "SELECT \"chargerCurrent\" * \"batteryVoltage\" FROM \"solarthing\" WHERE (\"packetType\" = 'MXFM_STATUS') AND $timeFilter GROUP BY \"identifier\"",
     "queryText": "{\n  data:queryStatus(from:\"$timeFrom\", to:\"$timeTo\", sourceId:\"default\") {\n    mxStatus {\n      Time:dateMillis\n      packet {\n        chargingPower\n        identifier {representation}\n        identityInfo { displayName }\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "chargerCurrent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "MXFM_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Generator Pass Thru",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "[[tag_identifier]]",
     "aliasBy": "$field_packet.identityInfo.displayName",
     "constant": 6.5,
     "dataPath": "data.fxStatus",
     "groupBy": "packet.identifier.representation",
     "measurement": "solarthing",
     "query": "SELECT (\"buyCurrent\" - \"chargerCurrent\") * \"inputVoltage\" FROM \"solarthing\" WHERE (\"packetType\" = 'FX_STATUS') AND $timeFilter GROUP BY \"identifier\"",
     "queryText": "{\n  data:queryStatus(from:\"$timeFrom\", to:\"$timeTo\", sourceId:\"default\") {\n    fxStatus {\n      Time:dateMillis\n      packet {\n        passThruWattage\n        identifier {representation}\n        identityInfo { displayName }\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "chargerCurrent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "FX_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Temperature (F)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "farenheit" }
   ],
   "targets": [
    {
     "alias": "Raspberry Pi #[[tag_fragmentId]]",
     "aliasBy": "$fieldName",
     "constant": 6.5,
     "dataPath": "data.roverStatus",
     "groupBy": "packet.identifier.representation",
     "measurement": "solarthing",
     "queryText": "{\n  data:queryStatus(from:\"$timeFrom\", to:\"$timeTo\", sourceId:\"default\") {\n    roverStatus {\n      Time:dateMillis\n      packet {\n        batteryTemperatureFahrenheit\n        controllerTemperatureFahrenheit\n        identifier {representation}\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "cpuTemperatureFahrenheit" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "DEVICE_CPU_TEMPERATURE" }
     ]
    }
   ]
  },
  {
   "title": "AC Mode Graph (Is Generator on or off?)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Mode" }
   ],
   "targets": [
    {
     "alias": "AC Mode | 0: No AC | 1: AC Drop | 2: AC Use",
     "aliasBy": "0: No AC | 1: AC Drop | 2: AC Use",
     "constant": 6.5,
     "dataPath": "data.fxStatus",
     "measurement": "solarthing",
     "queryText": "{\n  data:queryStatus(from:\"$timeFrom\", to:\"$timeTo\", sourceId:\"default\") {\n    fxStatus {\n      Time:dateMillis\n      packet {\n        acMode\n        identifier {representation}\n        identityInfo { displayName }\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "acMode" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "FX_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Energy Used Over Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "$tag_identifier",
     "aliasBy": "$field_packet.identityInfo.displayName",
     "constant": 6.5,
     "dataPath": "data.fxDaily",
     "groupBy": "packet.identifier.representation",
     "measurement": "solarthing",
     "queryText": "{\n  data:queryStatus(from:\"$timeFrom\", to:\"$timeTo\", sourceId:\"default\") {\n    fxDaily {\n      Time:dateMillis\n      packet {\n        inverterKWH\n        identifier {representation}\n        identityInfo { displayName }\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "inverterKWH" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "FX_DAILY" }
     ]
    }
   ]
  },
  {
   "title": "CPU Temperature (F)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "farenheit" }
   ],
   "targets": [
    {
     "alias": "$col  [[tag_identifier]]",
     "aliasBy": "Raspberry Pi #$field_fragmentIdString",
     "constant": 6.5,
     "dataPath": "data.cpuTemperature",
     "groupBy": "fragmentIdString",
     "measurement": "solarthing",
     "queryText": "{\n  data:queryStatus(from:\"$timeFrom\", to:\"$timeTo\", sourceId:\"default\") {\n    cpuTemperature {\n      Time:dateMillis\n      fragmentIdString\n      packet {\n        cpuTemperatureFahrenheit\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "batteryTemperatureRaw" ], "type": "field" },
       { "params": [ "*9/5 +32" ], "type": "math" },
       { "params": [ "Batteries" ], "type": "alias" }
      ],
      [
       { "params": [ "controllerTemperatureRaw" ], "type": "field" },
       { "params": [ "*9/5 +32" ], "type": "math" },
       { "params": [ "Controller" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "RENOGY_ROVER_STATUS" }
     ]
    }
   ]
  }
 ]
}