{
 "title": "SolarThing Dashboard",
 "description": "The SolarThing dashboard that shows the status of the solar panels and batteries.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "sourceId", "label": "Source ID", "query": "default,cabin" }
  ]
 },
 "panels": [
  {
   "title": "Battery Voltage",
   "type": "gauge",
   "description": "An average of devices able to give battery voltage readings.\n\nIf the voltage is below 23.0 V, this means the battery is low. If the voltage stays at or below 22.0 V for 2 minutes, the system will shutdown.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data.batteryVoltage",
     "measurement": "solarthing",
     "queryText": "{\n  data:queryStatusLast(to:\"$__to\", sourceId:\"$sourceId\") {\n    batteryVoltage {\n      Time:dateMillis\n      packet {\n        batteryVoltage\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "batteryVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature Data",
   "type": "stat",
   "description": "Shows temperature data for sensors connected to the SolarThing network.",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aliasBy": "$field_meta.name",
     "constant": 6.5,
     "dataPath": "data.temperature",
     "groupBy": "fragmentIdString,packet.identifier.representation",
     "queryText": "{\n        data:queryStatusLast(to:\"$__to\") {\n            temperature {\n                Time:dateMillis\n                fragmentIdString\n                packet {\n                    temperatureFahrenheit\n                    identifier { representation }\n                    identityInfo { displayName }\n                }\n                meta {\n                  name\n                }\n            }\n        }\n    }"
    },
    {
     "aliasBy": "Battery Temperature",
     "constant": 6.5,
     "dataPath": "data.roverStatus",
     "queryText": "{\n  data:queryStatusLast(to:\"$__to\", sourceId:\"default\") {\n    roverStatus {\n      Time:dateMillis\n      packet {\n        batteryTemperatureFahrenheit\n        identifier {representation}\n      }\n    }\n  }\n}"
    }
   ]
  },
  {
   "title": "PV Wattage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "[[tag_identifier]]",
     "aliasBy": "Wattage",
     "constant": 6.5,
     "dataPath": "data.solar",
     "measurement": "solarthing",
     "query": "SELECT \"pvCurrent\" * \"inputVoltage\" FROM \"solarthing\" WHERE (\"packetType\" = 'MXFM_STATUS') AND $timeFilter GROUP BY \"identifier\"",
     "queryText": "{\n  data:queryStatusLast(to:\"$__to\", sourceId:\"$sourceId\") {\n    solar {\n      Time:dateMillis\n      packet {\n        pvWattage\n        identifier {representation}\n        identityInfo { displayName }\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "pvCurrent" ], "type": "field" }
      ],
      [
       { "params": [ "inputVoltage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "MXFM_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "[[tag_identifier]]",
     "aliasBy": "Power Usage",
     "constant": 6.5,
     "dataPath": "data.fxStatus",
     "measurement": "solarthing",
     "query": "SELECT (\"inverterCurrent\" * \"outputVoltage\") + (\"buyCurrent\" - \"chargerCurrent\") * \"inputVoltage\" FROM \"solarthing\" WHERE (\"packetType\" = 'FX_STATUS') AND $timeFilter GROUP BY \"identifier\"",
     "queryText": "{\n  data:queryStatusLast(to:\"$timeTo\", sourceId:\"$sourceId\") {\n    fxStatus {\n      Time:dateMillis\n      packet {\n        powerUsageWattage\n        identifier {representation}\n        identityInfo { displayName }\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "inverterCurrent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "FX_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Daily kWH",
   "type": "gauge",
   "description": "This shows how much energy the solar panels have produced today. If the solar panels produced 1kW for 1 hour, that would be 1kWh.\n\nFor extremely sunny days with no clouds, we would usually get 14kWh.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "MX: [[tag_identifier]]",
     "constant": 6.5,
     "dataPath": "data.data",
     "measurement": "solarthing",
     "query": "SELECT \"dailyKWH\" FROM \"solarthing\" WHERE (\"packetType\" = 'MXFM_DAILY') AND $timeFilter GROUP BY \"identifier\"",
     "queryText": "{\n  data:queryFullDay(from:\"$__to\", to:\"$__to\", sourceId:\"default\") {\n    data:dailyKWHSum {\n      Time:dateMillis\n      data\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "dailyKWH" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "MXFM_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Battery Voltages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "aliasBy": "$field_packet.identityInfo.displayName",
     "constant": 6.5,
     "dataPath": "data.batteryVoltage",
     "groupBy": "packet.identifier.representation",
     "queryText": "{\n        data:queryStatus(from:\"$__from\", to:\"$__to\", sourceId:\"$sourceId\") {\n            batteryVoltage {\n                Time:dateMillis\n                packet {\n                    batteryVoltage\n                    identifier { representation }\n                    identityInfo { displayName }\n                }\n            }\n        }\n    }"
    }
   ]
  },
  {
   "title": "PV Wattage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "[[tag_identifier]]",
     "aliasBy": "$field_packet.identityInfo.displayName",
     "constant": 6.5,
     "dataPath": "data.solar",
     "groupBy": "packet.identifier.representation,fragmentIdString",
     "measurement": "solarthing",
     "query": "SELECT \"pvCurrent\" * \"inputVoltage\" FROM \"solarthing\" WHERE (\"packetType\" = 'MXFM_STATUS') AND $timeFilter GROUP BY \"identifier\"",
     "queryText": "{\n  data:queryStatusLast(to:\"$__to\", sourceId:\"$sourceId\") {\n    solar {\n      Time:dateMillis\n      fragmentIdString\n      packet {\n        pvWattage\n        identifier {representation}\n        identityInfo { displayName }\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "pvCurrent" ], "type": "field" }
      ],
      [
       { "params": [ "inputVoltage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "MXFM_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Device Mode",
   "type": "table-old",
   "description": "The mode that each device is in",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 5 },
   "targets": [
    {
     "alias": "[[tag_identifier]]",
     "constant": 6.5,
     "dataPath": "data.fxStatus, data.mxStatus, data.roverStatus",
     "groupBy": "packet.identifier.representation",
     "measurement": "solarthing",
     "query": "SELECT \"operatingModeName\" FROM \"normal_short_retention\".\"solarthing\" WHERE (\"packetType\" = 'FX_STATUS') AND $timeFilter GROUP BY \"identifier\" ORDER BY DESC LIMIT 1",
     "queryText": "{\n  data:queryStatusLast(to:\"$__to\", sourceId:\"$sourceId\", reversed: true) {\n    fxStatus {\n      packet {\n        identityInfo { displayName }\n        modeName:operatingModeName\n        identifier { representation }\n      }\n    }\n    mxStatus {\n      packet {\n        identityInfo { displayName }\n        modeName:chargerModeName\n        identifier { representation }\n      }\n    }\n\n    roverStatus {\n      packet {\n        identityInfo { displayName }\n        modeName:chargingStateName\n        identifier { representation }\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "operatingModeName" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "FX_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Solcast kWh Forecasts",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aliasBy": "Today's Forecast",
     "constant": 6.5,
     "dataPath": "data.data",
     "queryText": "query {\n      data:querySolcastDay(to:\"$__to\", sourceId:\"$sourceId\"){\n          data:queryEnergyEstimate {\n             Time:dayStart\n             dailyKWH\n          }\n      }\n}"
    },
    {
     "aliasBy": "Tomorrow's Forecast",
     "constant": 6.5,
     "dataPath": "data.data",
     "queryText": "query {\n      data:querySolcastDay(to:\"$__to\", sourceId:\"$sourceId\"){\n          data:queryEnergyEstimate(offset:1) {\n             Time:dayStart\n             dailyKWH\n          }\n      }\n}"
    },
    {
     "aliasBy": "Day After Tomorrow",
     "constant": 6.5,
     "dataPath": "data.data",
     "queryText": "query {\n      data:querySolcastDay(to:\"$__to\", sourceId:\"$sourceId\"){\n          data:queryEnergyEstimate(offset:2) {\n             Time:dayStart\n             dailyKWH\n          }\n      }\n}"
    }
   ]
  },
  {
   "title": "PV Wattage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "[[tag_identifier]]",
     "aliasBy": "$field_packet.identityInfo.displayName wattage",
     "constant": 6.5,
     "dataPath": "data.solar",
     "groupBy": "packet.identifier.representation",
     "measurement": "solarthing",
     "query": "SELECT \"pvCurrent\" * \"inputVoltage\" FROM \"solarthing\" WHERE (\"packetType\" = 'MXFM_STATUS') AND $timeFilter GROUP BY \"identifier\"",
     "queryText": "{\n  data:queryStatus(from:\"$__from\", to:\"$__to\", sourceId:\"$sourceId\") {\n    solar {\n      Time:dateMillis\n      packet {\n        pvWattage\n        identifier {representation}\n        identityInfo { displayName }\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "pvCurrent" ], "type": "field" }
      ],
      [
       { "params": [ "inputVoltage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "MXFM_STATUS" }
     ]
    },
    {
     "aliasBy": "Solcast Prediction",
     "constant": 6.5,
     "dataPath": "data.queryForecasts",
     "queryText": "{\n  data:querySolcast(from:\"$__from\", to:\"$__to\", sourceId:\"$sourceId\") {\n    queryForecasts(includePast:false) {\n      Time:period_end\n      pv_estimate_watts\n    }\n  }\n}"
    }
   ]
  },
  {
   "title": "Daily kWH",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "MX: [[tag_identifier]]",
     "aliasBy": "$field_identifiable.identityInfo.displayName",
     "constant": 6.5,
     "dataPath": "data.data",
     "groupBy": "fragmentIdString, identifiable.identifier.representation",
     "measurement": "solarthing",
     "query": "SELECT \"dailyKWH\" FROM \"solarthing\" WHERE (\"packetType\" = 'MXFM_DAILY') AND $timeFilter GROUP BY \"identifier\"",
     "queryText": "{\n  data:queryFullDay(from:\"$__from\", to:\"$__to\", sourceId:\"default\") {\n    data:dailyKWH {\n      Time:dateMillis\n      data\n      fragmentIdString\n      identifiable { \n        identifier { representation } \n        identityInfo {displayName }\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "dailyKWH" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "MXFM_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "[[tag_identifier]]",
     "aliasBy": "$field_packet.identityInfo.displayName",
     "constant": 6.5,
     "dataPath": "data.fxStatus",
     "groupBy": "packet.identifier.representation",
     "measurement": "solarthing",
     "query": "SELECT (\"inverterCurrent\" * \"outputVoltage\") + (\"buyCurrent\" - \"chargerCurrent\") * \"inputVoltage\" FROM \"solarthing\" WHERE (\"packetType\" = 'FX_STATUS') AND $timeFilter GROUP BY \"identifier\"",
     "queryText": "{\n  data:queryStatus(from:\"$__from\", to:\"$__to\", sourceId:\"default\") {\n    fxStatus {\n      Time:dateMillis\n      packet {\n        powerUsageWattage\n        identifier {representation}\n        identityInfo { displayName }\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "inverterCurrent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "FX_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Generator Charging",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "[[tag_identifier]]",
     "aliasBy": "$field_packet.identityInfo.displayName",
     "constant": 6.5,
     "dataPath": "data.fxStatus",
     "groupBy": "packet.identifier.representation",
     "measurement": "solarthing",
     "query": "SELECT \"chargerCurrent\" * \"inputVoltage\" FROM \"solarthing\" WHERE (\"packetType\" = 'FX_STATUS') AND $timeFilter GROUP BY \"identifier\"",
     "queryText": "{\n  data:queryStatus(from:\"$__from\", to:\"$__to\", sourceId:\"default\") {\n    fxStatus {\n      Time:dateMillis\n      packet {\n        chargerWattage\n        identifier {representation}\n        identityInfo { displayName }\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "chargerCurrent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "FX_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Load on Battery",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "[[tag_identifier]]",
     "aliasBy": "$field_packet.identityInfo.displayName",
     "constant": 6.5,
     "dataPath": "data.fxStatus",
     "groupBy": "packet.identifier.representation",
     "measurement": "solarthing",
     "query": "SELECT \"inverterCurrent\" * \"outputVoltage\" FROM \"solarthing\" WHERE (\"packetType\" = 'FX_STATUS') AND $timeFilter GROUP BY \"identifier\"",
     "queryText": "{\n  data:queryStatus(from:\"$__from\", to:\"$__to\", sourceId:\"default\") {\n    fxStatus {\n      Time:dateMillis\n      packet {\n        inverterWattage\n        identifier {representation}\n        identityInfo { displayName }\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "inverterCurrent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "FX_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Generator Buying",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "[[tag_identifier]]",
     "aliasBy": "$field_packet.identityInfo.displayName",
     "constant": 6.5,
     "dataPath": "data.fxStatus",
     "groupBy": "packet.identifier.representation",
     "measurement": "solarthing",
     "query": "SELECT \"buyCurrent\" * \"inputVoltage\" FROM \"solarthing\" WHERE (\"packetType\" = 'FX_STATUS') AND $timeFilter GROUP BY \"identifier\"",
     "queryText": "{\n  data:queryStatus(from:\"$timeFrom\", to:\"$timeTo\", sourceId:\"default\") {\n    fxStatus {\n      Time:dateMillis\n      packet {\n        buyWattage\n        identifier {representation}\n        identityInfo { displayName }\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "chargerCurrent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "FX_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Charger Wattage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "aliasBy": "$field_packet.identityInfo.displayName",
     "constant": 6.5,
     "dataPath": "data.chargeController",
     "groupBy": "packet.identifier.representation",
     "measurement": "solarthing",
     "query": "SELECT \"chargerCurrent\" * \"batteryVoltage\" FROM \"solarthing\" WHERE (\"packetType\" = 'MXFM_STATUS') AND $timeFilter GROUP BY \"identifier\"",
     "queryText": "{\n  data:queryStatus(from:\"$timeFrom\", to:\"$timeTo\", sourceId:\"default\") {\n    chargeController {\n      Time:dateMillis\n      packet {\n        chargingPower\n        identifier {representation}\n        identityInfo { displayName }\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "chargerCurrent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "MXFM_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Generator Pass Thru",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "[[tag_identifier]]",
     "aliasBy": "$field_packet.identityInfo.displayName",
     "constant": 6.5,
     "dataPath": "data.fxStatus",
     "groupBy": "packet.identifier.representation",
     "measurement": "solarthing",
     "query": "SELECT (\"buyCurrent\" - \"chargerCurrent\") * \"inputVoltage\" FROM \"solarthing\" WHERE (\"packetType\" = 'FX_STATUS') AND $timeFilter GROUP BY \"identifier\"",
     "queryText": "{\n  data:queryStatus(from:\"$__from\", to:\"$__to\", sourceId:\"default\") {\n    fxStatus {\n      Time:dateMillis\n      packet {\n        passThruWattage\n        identifier {representation}\n        identityInfo { displayName }\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "chargerCurrent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "FX_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Temperature (F)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "farenheit" }
   ],
   "targets": [
    {
     "alias": "Raspberry Pi #[[tag_fragmentId]]",
     "aliasBy": "$fieldName",
     "constant": 6.5,
     "dataPath": "data.roverStatus",
     "groupBy": "packet.identifier.representation",
     "measurement": "solarthing",
     "queryText": "{\n  data:queryStatus(from:\"$__from\", to:\"$__to\", sourceId:\"default\") {\n    roverStatus {\n      Time:dateMillis\n      packet {\n        batteryTemperatureFahrenheit\n        controllerTemperatureFahrenheit\n        identifier {representation}\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "cpuTemperatureFahrenheit" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "DEVICE_CPU_TEMPERATURE" }
     ]
    }
   ]
  },
  {
   "title": "AC Mode Graph (Is Generator on or off?)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "Mode" }
   ],
   "targets": [
    {
     "alias": "AC Mode | 0: No AC | 1: AC Drop | 2: AC Use",
     "aliasBy": "0: No AC | 1: AC Drop | 2: AC Use",
     "constant": 6.5,
     "dataPath": "data.fxStatus",
     "measurement": "solarthing",
     "queryText": "{\n  data:queryStatus(from:\"$__from\", to:\"$__to\", sourceId:\"default\") {\n    fxStatus {\n      Time:dateMillis\n      packet {\n        acMode\n        identifier {representation}\n        identityInfo { displayName }\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "acMode" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "FX_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Energy Used Over Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "$tag_identifier",
     "aliasBy": "$field_packet.identityInfo.displayName",
     "constant": 6.5,
     "dataPath": "data.fxDaily",
     "groupBy": "packet.identifier.representation",
     "measurement": "solarthing",
     "queryText": "{\n  data:queryStatus(from:\"$__from\", to:\"$__to\", sourceId:\"default\") {\n    fxDaily {\n      Time:dateMillis\n      packet {\n        inverterKWH\n        identifier {representation}\n        identityInfo { displayName }\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "inverterKWH" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "FX_DAILY" }
     ]
    }
   ]
  },
  {
   "title": "CPU Temperature (F)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "farenheit" }
   ],
   "targets": [
    {
     "alias": "$col  [[tag_identifier]]",
     "aliasBy": "$field_fragmentDeviceInfo.deviceName",
     "constant": 6.5,
     "dataPath": "data.cpuTemperature",
     "groupBy": "fragmentIdString",
     "measurement": "solarthing",
     "queryText": "{\n  data:queryStatus(from:\"$__from\", to:\"$__to\") {\n    cpuTemperature {\n      Time:dateMillis\n      fragmentIdString\n      packet {\n        cpuTemperatureFahrenheit\n      }\n      fragmentDeviceInfo {\n        deviceName\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "batteryTemperatureRaw" ], "type": "field" },
       { "params": [ "*9/5 +32" ], "type": "math" },
       { "params": [ "Batteries" ], "type": "alias" }
      ],
      [
       { "params": [ "controllerTemperatureRaw" ], "type": "field" },
       { "params": [ "*9/5 +32" ], "type": "math" },
       { "params": [ "Controller" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "RENOGY_ROVER_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Battery Voltages Temperature Compensated",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "aliasBy": "$field_identifiable.identityInfo.displayName",
     "constant": 6.5,
     "dataPath": "data.batteryVoltageTemperatureCompensated",
     "groupBy": "identifiable.identifier.representation",
     "queryText": "{\n        data:queryStatus(from:\"$__from\", to:\"$__to\", sourceId:\"default\") {\n            batteryVoltageTemperatureCompensated {\n                Time:dateMillis\n                data\n                identifiable {\n                    identifier { representation }\n                    identityInfo { displayName }\n                }\n            }\n        }\n    }"
    }
   ]
  },
  {
   "title": "PV Overview",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "[[tag_identifier]]",
     "aliasBy": "$field_packet.identityInfo.displayName wattage",
     "constant": 6.5,
     "dataPath": "data.chargeController",
     "groupBy": "packet.identifier.representation",
     "measurement": "solarthing",
     "query": "SELECT \"pvCurrent\" * \"inputVoltage\" FROM \"solarthing\" WHERE (\"packetType\" = 'MXFM_STATUS') AND $timeFilter GROUP BY \"identifier\"",
     "queryText": "{\n  data:queryStatus(from:\"$__from\", to:\"$__to\", sourceId:\"default\") {\n    chargeController {\n      Time:dateMillis\n      packet {\n        pvWattage\n        identifier {representation}\n        identityInfo { displayName }\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "pvCurrent" ], "type": "field" }
      ],
      [
       { "params": [ "inputVoltage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "MXFM_STATUS" }
     ]
    },
    {
     "aliasBy": "$field_packet.identityInfo.displayName PV voltage",
     "constant": 6.5,
     "dataPath": "data.chargeController",
     "groupBy": "packet.identifier.representation",
     "queryText": "{\n  data:queryStatus(from:\"$timeFrom\", to:\"$timeTo\", sourceId:\"default\") {\n    chargeController {\n      Time:dateMillis\n      packet {\n        pvVoltage\n        identifier {representation}\n        identityInfo { displayName }\n      }\n    }\n  }\n}"
    },
    {
     "alias": "[[tag_identifier]]",
     "aliasBy": "$field_packet.identityInfo.displayName charger",
     "constant": 6.5,
     "dataPath": "data.chargeController",
     "groupBy": "packet.identifier.representation",
     "measurement": "solarthing",
     "query": "SELECT \"pvCurrent\" * \"inputVoltage\" FROM \"solarthing\" WHERE (\"packetType\" = 'MXFM_STATUS') AND $timeFilter GROUP BY \"identifier\"",
     "queryText": "{\n  data:queryStatus(from:\"$timeFrom\", to:\"$timeTo\", sourceId:\"default\") {\n    chargeController {\n      Time:dateMillis\n      packet {\n        chargingPower\n        identifier {representation}\n        identityInfo { displayName }\n      }\n    }\n  }\n}",
     "select": [
      [
       { "params": [ "pvCurrent" ], "type": "field" }
      ],
      [
       { "params": [ "inputVoltage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "MXFM_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Temperature Data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "aliasBy": "$field_meta.name",
     "constant": 6.5,
     "dataPath": "data.temperature",
     "groupBy": "fragmentIdString,packet.dataIdString",
     "queryText": "{\n        data:queryStatus(from: \"$__from\" to:\"$__to\") {\n            temperature {\n                Time:dateMillis\n                fragmentIdString\n                packet {\n                    temperatureFahrenheit\n                    dataIdString\n                    identifier { representation }\n                    identityInfo { displayName }\n                }\n                meta {\n                  name\n                }\n            }\n        }\n    }"
    }
   ]
  },
  {
   "title": "FX Timers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aliasBy": "$fieldName",
     "constant": 6.5,
     "dataPath": "data",
     "queryText": "{\n        data:queryFXCharging(from: \"$__from\" to:\"$__to\" fragmentId:1) {\n            Time:dateMillis\n            data {\n              remainingAbsorbTimeMillis\n              remainingFloatTimeMillis\n              remainingEqualizeTimeMillis\n            }\n        }\n    }"
    }
   ]
  },
  {
   "title": "Remaining Generator Time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aliasBy": "$fieldName",
     "constant": 6.5,
     "dataPath": "data",
     "queryText": "{\n        data:queryFXCharging(from: \"$__from\" to:\"$__to\" fragmentId:1) {\n            Time:dateMillis\n            data {\n              remainingAbsorbTimeMillis\n            }\n        }\n    }"
    }
   ]
  }
 ]
}