plugins {
    id("buildlogic.java-common-conventions")
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

version = "0.0.1-SNAPSHOT"

dependencies {
    annotationProcessor "com.google.auto.service:auto-service:1.1.1"
    implementation("com.google.auto.service:auto-service:1.1.1")
}
