#!/usr/bin/env sh

BASEDIR=$(dirname "$0")

java -jar "$BASEDIR/../solarthing.jar" "$@"
# It is important that we do not have any more commands after this because we want the exit code
#   to be the same as the exit code of the java command
