#!/usr/bin/env bash
# This version of the solarthing command can be used while debugging and while running programs that don't need logs

BASEDIR=$(dirname "$0")

"$BASEDIR/../.scripts/download_if_needed.sh" || exit 1

# see https://logging.apache.org/log4j/2.x/manual/configuration.html#system-properties
export LOG4J_CONFIGURATION_FILE="$BASEDIR"/../../config_templates/log/console_only_and_no_debug_log4j2.xml

export SOLARTHING_ROOT="$BASEDIR/../.."
source "$BASEDIR/../.scripts/use_sdkman_if_available.sh" # Requires bash

"$BASEDIR/../.bin/raw_solarthing" "$@"
