{
 "title": "Default SolarThing Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Battery Voltages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "[[tag_identifier]]",
     "groupBy": [
      { "params": [ "identifier" ], "type": "tag" }
     ],
     "measurement": "solarthing",
     "select": [
      [
       { "params": [ "batteryVoltage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "solarthing",
     "select": [
      [
       { "params": [ "batteryVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Device Mode",
   "type": "table",
   "description": "The mode that each device is in",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "alias": "[[tag_identifier]]",
     "groupBy": [
      { "params": [ "identifier" ], "type": "tag" }
     ],
     "measurement": "solarthing",
     "query": "SELECT \"operatingModeName\" FROM \"normal_short_retention\".\"solarthing\" WHERE (\"packetType\" = 'FX_STATUS') AND $timeFilter GROUP BY \"identifier\" ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "operatingModeName" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "FX_STATUS" }
     ]
    },
    {
     "alias": "[[tag_identifier]]",
     "groupBy": [
      { "params": [ "identifier" ], "type": "tag" }
     ],
     "measurement": "solarthing",
     "query": "SELECT \"chargerModeName\" FROM \"normal_short_retention\".\"solarthing\" WHERE (\"packetType\" = 'MXFM_STATUS') AND $timeFilter GROUP BY \"identifier\" ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "chargerModeName" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "MXFM_STATUS" }
     ]
    },
    {
     "alias": "[[tag_identifier]]",
     "groupBy": [
      { "params": [ "identifier" ], "type": "tag" }
     ],
     "measurement": "solarthing",
     "query": "SELECT \"chargingStateName\" FROM \"normal_short_retention\".\"solarthing\" WHERE (\"packetType\" = 'RENOGY_ROVER_STATUS') AND $timeFilter GROUP BY \"identifier\" ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "chargerModeName" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "MXFM_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "PV Wattage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "[[tag_identifier]]",
     "groupBy": [
      { "params": [ "identifier" ], "type": "tag" }
     ],
     "measurement": "solarthing",
     "query": "SELECT \"pvCurrent\" * \"inputVoltage\" FROM \"solarthing\" WHERE (\"packetType\" = 'MXFM_STATUS') AND $timeFilter GROUP BY \"identifier\"",
     "select": [
      [
       { "params": [ "pvCurrent" ], "type": "field" }
      ],
      [
       { "params": [ "inputVoltage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "MXFM_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Daily kWH",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "MX: [[tag_identifier]]",
     "groupBy": [
      { "params": [ "identifier" ], "type": "field" }
     ],
     "measurement": "solarthing",
     "query": "SELECT \"dailyKWH\" FROM \"solarthing\" WHERE (\"packetType\" = 'MXFM_STATUS') AND $timeFilter GROUP BY \"identifier\"",
     "select": [
      [
       { "params": [ "dailyKWH" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "MXFM_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "[[tag_identifier]]",
     "groupBy": [
      { "params": [ "identifier" ], "type": "tag" }
     ],
     "measurement": "solarthing",
     "query": "SELECT (\"inverterCurrent\" * \"outputVoltage\") + (\"buyCurrent\" - \"chargerCurrent\") * \"inputVoltage\" FROM \"solarthing\" WHERE (\"packetType\" = 'FX_STATUS') AND $timeFilter GROUP BY \"identifier\"",
     "select": [
      [
       { "params": [ "inverterCurrent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "FX_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Generator Charging",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "[[tag_identifier]]",
     "groupBy": [
      { "params": [ "identifier" ], "type": "tag" }
     ],
     "measurement": "solarthing",
     "query": "SELECT \"chargerCurrent\" * \"inputVoltage\" FROM \"solarthing\" WHERE (\"packetType\" = 'FX_STATUS') AND $timeFilter GROUP BY \"identifier\"",
     "select": [
      [
       { "params": [ "chargerCurrent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "FX_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Load on Battery",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "[[tag_identifier]]",
     "groupBy": [
      { "params": [ "identifier" ], "type": "tag" }
     ],
     "measurement": "solarthing",
     "query": "SELECT \"inverterCurrent\" * \"outputVoltage\" FROM \"solarthing\" WHERE (\"packetType\" = 'FX_STATUS') AND $timeFilter GROUP BY \"identifier\"",
     "select": [
      [
       { "params": [ "inverterCurrent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "FX_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Generator Buying",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "[[tag_identifier]]",
     "groupBy": [
      { "params": [ "identifier" ], "type": "tag" }
     ],
     "measurement": "solarthing",
     "query": "SELECT \"buyCurrent\" * \"inputVoltage\" FROM \"solarthing\" WHERE (\"packetType\" = 'FX_STATUS') AND $timeFilter GROUP BY \"identifier\"",
     "select": [
      [
       { "params": [ "chargerCurrent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "FX_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Temperature (F)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "farenheit" }
   ],
   "targets": [
    {
     "alias": "$col  [[tag_identifier]]",
     "groupBy": [
      { "params": [ "identifier" ], "type": "tag" }
     ],
     "measurement": "solarthing",
     "select": [
      [
       { "params": [ "batteryTemperatureRaw" ], "type": "field" },
       { "params": [ "*9/5 +32" ], "type": "math" },
       { "params": [ "Batteries" ], "type": "alias" }
      ],
      [
       { "params": [ "controllerTemperatureRaw" ], "type": "field" },
       { "params": [ "*9/5 +32" ], "type": "math" },
       { "params": [ "Controller" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "RENOGY_ROVER_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Generator Pass Thru",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "[[tag_identifier]]",
     "groupBy": [
      { "params": [ "identifier" ], "type": "tag" }
     ],
     "measurement": "solarthing",
     "query": "SELECT (\"buyCurrent\" - \"chargerCurrent\") * \"inputVoltage\" FROM \"solarthing\" WHERE (\"packetType\" = 'FX_STATUS') AND $timeFilter GROUP BY \"identifier\"",
     "select": [
      [
       { "params": [ "chargerCurrent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "FX_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Charger Wattage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "identifier" ], "type": "tag" }
     ],
     "measurement": "solarthing",
     "query": "SELECT \"chargerCurrent\" * \"batteryVoltage\" FROM \"solarthing\" WHERE (\"packetType\" = 'MXFM_STATUS') AND $timeFilter GROUP BY \"identifier\"",
     "select": [
      [
       { "params": [ "chargerCurrent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "MXFM_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "AC Mode Graph (Is Generator on or off?)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Mode" }
   ],
   "targets": [
    {
     "alias": "AC Mode | 0: No AC | 1: AC Drop | 2: AC Use",
     "measurement": "solarthing",
     "select": [
      [
       { "params": [ "acMode" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "FX_STATUS" }
     ]
    }
   ]
  },
  {
   "title": "Energy Used Over Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "$tag_identifier",
     "groupBy": [
      { "params": [ "identifier" ], "type": "tag" }
     ],
     "measurement": "solarthing",
     "select": [
      [
       { "params": [ "inverterKWH" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "packetType", "operator": "=", "value": "FX_DAILY" }
     ]
    }
   ]
  }
 ]
}